src/Entity/Activiteiten.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * Activiteiten
 *
 * @ORM\Table(name="activiteiten")
 * @ORM\Entity(repositoryClass="App\Repository\ActiviteitenRepository")
 */
class Activiteiten
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datum", type="date")
     * @Assert\NotBlank(message="vul een datum in")
     *
     */
    private $datum;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="tijd", type="time")
     * @Assert\NotBlank(message="vul een tijd in")
     *
     */
    private $tijd;

    /**
     * @ORM\ManyToOne(targetEntity="Soortactiviteiten", inversedBy="activiteiten")
     * @ORM\JoinColumn(name="soort_id",referencedColumnName="id")
     *
     */

    private $soort;

    /**
     * Many Activiteiten have Many Users.
     * @ORM\ManyToMany(targetEntity="User", mappedBy="activiteiten")
     */

    private $users;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set datum
     *
     * @param \DateTime $datum
     *
     * @return Activiteiten
     */
    public function setDatum($datum)
    {

        $this->datum = $datum;

        return $this;
    }

    /**
     * Get datum
     *
     * @return \DateTime
     */
    public function getDatum()
    {
        return $this->datum;
    }

    /**
     * Set tijd
     *
     * @param \DateTime $tijd
     *
     * @return Activiteiten
     */
    public function setTijd($tijd)
    {
        $this->tijd = $tijd;

        return $this;
    }

    /**
     * Get tijd
     *
     * @return \DateTime
     */
    public function getTijd()
    {
        return $this->tijd;
    }

    public function getSoort()
    {
        return $this->soort;
    }

    public function setSoort($soort)
    {
        $this->soort=$soort;
    }

    public function getMaxUsers(): ?int
    {
        return $this->max_users;
    }

    public function setMaxUsers(int $max_users): self
    {
        $this->max_users = $max_users;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

//use Doctrine\ORM\Mapping as ORM;
//use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $voorletters;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tussenvoegsel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $achternaam;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $woonplaats;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telefoon;

    /**
     * @Assert\Length(max=4096)
     * @Assert\NotBlank(message="vul wachtwoord in")
     */
    private $plainPassword;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Many Users have Many Activities.
     * @ORM\ManyToMany(targetEntity="Activiteiten", inversedBy="user")
     * @ORM\JoinTable(name="deelnames")
     */
    private $activiteiten;

    public function __construct()
    {
        $this->activiteiten = new \Doctrine\Common\Collections\ArrayCollection();
        $this->isActive = true;
    }

    public function addActiviteit(Activiteiten $a)
    {
        if ($this->activiteiten->contains($a)) {

            return;
        }

        $this->activiteiten->add($a);

    }

    public function removeActiviteit(Activiteiten $a)
    {
        if (!$this->activiteiten->contains($a)) {
            return;
        }
        $this->activiteiten->removeElement($a);
    }

    function getNaam()
    {
        return $this->voorletters." ".$this->tussenvoegsel." ".$this->achternaam;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getVoorletters(): ?string
    {
        return $this->voorletters;
    }

    public function setVoorletters(?string $voorletters): self
    {
        $this->voorletters = $voorletters;

        return $this;
    }

    public function getTussenvoegsel(): ?string
    {
        return $this->tussenvoegsel;
    }

    public function setTussenvoegsel(?string $tussenvoegsel): self
    {
        $this->tussenvoegsel = $tussenvoegsel;

        return $this;
    }

    public function getAchternaam(): ?string
    {
        return $this->achternaam;
    }

    public function setAchternaam(?string $achternaam): self
    {
        $this->achternaam = $achternaam;

        return $this;
    }

    public function getAdres(): ?string
    {
        return $this->adres;
    }

    public function setAdres(?string $adres): self
    {
        $this->adres = $adres;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(?string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getWoonplaats(): ?string
    {
        return $this->woonplaats;
    }

    public function setWoonplaats(?string $woonplaats): self
    {
        $this->woonplaats = $woonplaats;

        return $this;
    }

    public function getTelefoon(): ?string
    {
        return $this->telefoon;
    }

    public function setTelefoon(?string $telefoon): self
    {
        $this->telefoon = $telefoon;

        return $this;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }
}

src/Controller/DeelnemerController.php
<?php

namespace App\Controller;


use App\Entity\User;
use App\Form\UserAdminControlType;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DeelnemerController extends AbstractController
{
    /**
     * @Route("/user/activiteiten", name="activiteiten")
     */
    public function activiteitenAction()
    {
        $usr= $this->get('security.token_storage')->getToken()->getUser();

        $beschikbareActiviteiten=$this->getDoctrine()
            ->getRepository('App:Activiteiten')
            ->getBeschikbareActiviteiten($usr->getId());

        $ingeschrevenActiviteiten=$this->getDoctrine()
            ->getRepository('App:Activiteiten')
            ->getIngeschrevenActiviteiten($usr->getId());

        $totaal=$this->getDoctrine()
            ->getRepository('App:Activiteiten')
            ->getTotaal($ingeschrevenActiviteiten);


        return $this->render('deelnemer/activiteiten.html.twig', [
            'beschikbare_activiteiten'=>$beschikbareActiviteiten,
            'ingeschreven_activiteiten'=>$ingeschrevenActiviteiten,
            'totaal'=>$totaal,
        ]);
    }

    /**
     * @Route("/user/inschrijven/{id}", name="inschrijven")
     */
    public function inschrijvenActiviteitAction($id)
    {

        $activiteit = $this->getDoctrine()
            ->getRepository('App:Activiteiten')
            ->find($id);
        $usr= $this->get('security.token_storage')->getToken()->getUser();
        $usr->addActiviteit($activiteit);

        $em = $this->getDoctrine()->getManager();
        $em->persist($usr);
        $em->flush();

        return $this->redirectToRoute('activiteiten');
    }

    /**
     * @Route("/user/uitschrijven/{id}", name="uitschrijven")
     */
    public function uitschrijvenActiviteitAction($id)
    {
        $activiteit = $this->getDoctrine()
            ->getRepository('App:Activiteiten')
            ->find($id);
        $usr= $this->get('security.token_storage')->getToken()->getUser();
        $usr->removeActiviteit($activiteit);
        $em = $this->getDoctrine()->getManager();
        $em->persist($usr);
        $em->flush();
        return $this->redirectToRoute('activiteiten');
    }

    /**
     * @Route("/user/{id}/edit", name="user_bezoeker_edit", methods={"GET","POST"})
     */
    public function editUser(Request $request, User $user): Response
    {

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_bezoeker_edit');
        }

        return $this->render('user/edit_bezoeker.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

}

templates/deelnemer/activiteiten.html.twig
{% extends 'deelnemer.html.twig' %}
{% block menu %}
    <li class="active"><a href="{{ path('activiteiten') }}">home</a></li>
    <li><a href="{{ path('user_bezoeker_edit', {'id': app.user.id}) }}">Account</a></li>


{% endblock %}


{% block content %}
<section >
    <table class="table" style="table-layout: fixed" >
        <caption>
            Dit zijn alle beschikbare activiteiten
        </caption>
        <thead>
        <tr>
            <td>datum</td>
            <td>tijd</td>
            <td>soort activiteit</td>
            <td>prijs</td>
            <td>Plaatsen</td>
            <td>schrijf in</td>
        </tr>
        </thead>
        <tbody>
        {% for activiteit in beschikbare_activiteiten %}
            {% if date(activiteit.datum|date("d-m-Y") ~ activiteit.tijd|date("H:i")) >= date() %}
                <tr>
                    <td>
                        {{ activiteit.datum|date("d-m-Y")}}
                    </td>
                    <td>
                        {{ activiteit.tijd|date("H:i")}}
                    </td>

                    <td>
                        {{ activiteit.soort.naam}}
                    </td>
                    <td>
                        &euro;{{ activiteit.soort.prijs|number_format(2,',','.')}}
                    </td>
                    <td>
                        {{ activiteit.maxUsers - activiteit.users|length }}
                    </td>
                    <td title="schrijf in voor activiteit">


                        <{% if (activiteit.maxUsers - activiteit.users|length) <= 0 %}div{% else %}a{% endif %} href="{% if (activiteit.maxUsers - activiteit.users|length) > 0 %} {{ path('inschrijven', {'id':activiteit.id}) }} {% endif %}" >
                            <span class="glyphicon glyphicon-plus" style="{% if (activiteit.maxUsers - activiteit.users|length) <= 0 %}color:gray{% else %}color:red{% endif %}"></span>
                        </{% if (activiteit.maxUsers - activiteit.users|length) <= 0 %}div{% else %}a{% endif %}>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    <table class="table" style="table-layout: fixed">
        <caption>
            Dit zijn de door jou ingeschreven activiteiten
        </caption>
        <thead>
        <tr>
            <td>datum</td>
            <td>tijd</td>
            <td>soort activiteit</td>
            <td>prijs</td>
            <td>Plaatsen</td>
            <td>schrijf uit</td>
        </tr>
        </thead>
        <tbody>
        {% for activiteit in ingeschreven_activiteiten %}
            <tr>
                <td>
                    {{ activiteit.datum|date("d-m-Y")}}
                </td>
                <td>
                    {{ activiteit.tijd|date("H:i")}}
                </td>

                <td>
                    {{ activiteit.soort.naam}}
                </td>
                <td>
                    &euro;{{ activiteit.soort.prijs|number_format(2,',','.')}}
                </td>

                <td>
                    {{ activiteit.maxUsers - activiteit.users|length }}
                </td>
                <td title="schrijf in voor activiteit">
                    <a href="{{ path('uitschrijven', {'id':activiteit.id}) }}" >
                        <span class="glyphicon glyphicon-minus" style="color:red"></span>
                    </a>
                </td>

            </tr>
        {% endfor %}
        <tr>
            <td>
            </td>
            <td>
            </td>
            <td>
                Totaal prijs:
            </td>
            <td>
                &euro;{{totaal|number_format(2,',','.')}}

            </td>
            <td>
            </td>
        </tr>

        </tbody>
    </table>
</section>


{% endblock %}